version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
        interval: daily
        time: "09:00"
        timezone: Europe/Berlin
    open-pull-requests-limit: 10
    groups:
      babel:
        patterns:
          - "@babel*"
      storybook:
        patterns:
          - "@storybook*"
          - "storybook"
      # react and react-dom are needed for storybook, so the versions required by storybook should be installed
      react:
        patterns:
          - "react"
          - "react-dom"
      tiptap:
        patterns:
          - "@tiptap*"
      vue:
        patterns:
          - "vue"
          - "@vue/compiler-sfc"
          - "@vue/compat"
          - "@vue/server-renderer"
      vueuse:
        patterns:
          - "@vueuse*"
