type IconAlias =
  'ai' // alias for 'robot'
  | 'cancel' // alias for 'xmark' -> 'x'
  | 'chevron-down' // alias for 'caret-down'
  | 'chevron-left' // alias for 'caret-left'
  | 'chevron-right' // alias for 'caret-right'
  | 'chevron-up' // alias for 'caret-up'
  | 'close' // alias for 'xmark' -> 'x'
  | 'compress' // alias for 'corners-in'
  | 'delete' // alias for 'trash-simple'
  | 'download' // alias for 'download-simple'
  | 'drag-handle' // alias for 'dots-six-vertical'
  | 'edit' // alias for 'pencil-simple'
  | 'expand' // alias for 'corners-out'
  | 'history' // alias for 'clock-counter-clockwise'
  | 'lock' // alias for 'lock-simple'
  | 'mail' // alias for 'envelope-simple'
  | 'refresh' // alias for 'arrows-clockwise'
  | 'remove' // alias for 'xmark' -> 'x'
  | 'search' // alias for magnifying-glass
  | 'settings' // alias for 'gear-six', weight: fill
  | 'severe' // alias for 'warning-diamond'
  | 'spinner' // alias for circle-notch
  | 'success' // alias for 'check-circle'
  | 'unlock' // alias for 'lock-simple-open'
  | 'userSolid' // alias for 'user', weight: fill
  | 'xmark' // alias for 'x'


export type IconName =
  | 'arrow-down'
  | 'arrow-left'
  | 'arrow-right'
  | 'arrow-up'
  | 'caret-down'
  | 'caret-left'
  | 'caret-right'
  | 'caret-up'
  | 'caret-double-down'
  | 'caret-double-up'
  | 'check'
  | 'check-circle'
  | 'clock'
  | 'copy'
  | 'download-simple'
  | 'file'
  | 'highlighter'
  | 'hourglass'
  | 'info'
  | 'pencil-simple'
  | 'plus'
  | 'phone'
  | 'question'
  | 'robot'
  | 'signOut'
  | 'tag'
  | 'user'
  | 'usersThree'
  | 'warning'
  | 'warning-diamond'
  | 'x'
  | 'x-circle'
  | IconAlias

export type IconSize = 'small' | 'medium' | 'large' | 'xlarge'

export type IconWeight = 'light' | 'regular' | 'bold' | 'fill'
