let {
  DpButton,
  DpDetails,
  DpIcon,
  DpInput,
  DpLabel,
  DpLoading,
  dataTableSearch,
  DpAccordion,
  DpAnonymizeText,
  DpAutocomplete,
  DpBulkEditHeader,
  DpButtonIcon,
  DpButtonRow,
  DpCard,
  DpChangeStateAtDate,
  DpCheckbox,
  DpCheckboxGroup,
  DpColumnSelector,
  DpContextualHelp,
  DpCopyPasteButton,
  DpDashboardTaskCard,
  DpDataTable,
  DpDataTableExtended,
  DpDatepicker,
  DpDateRangePicker,
  DpDatetimePicker,
  DpEditableList,
  DpEditor,
  DpFlyout,
  DpFormRow,
  DpHeightLimit,
  DpInlineNotification,
  DpModal,
  DpMultiselect,
  DpNotifyContainer,
  DpObscure,
  DpPager,
  DpProgressBar,
  DpRadio,
  DpRegisterFlyout,
  DpResettableInput,
  DpSearchField,
  DpSelect,
  DpSelectPageItemCount,
  DpSkeletonBox,
  DpSlidebar,
  DpSlidingPagination,
  DpSplitButton,
  DpStickyElement,
  DpSwitcher,
  DpTab,
  DpTableCard,
  DpTableCardListHeader,
  DpTabs,
  DpTextArea,
  DpTextWrapper,
  DpTimePicker,
  DpToggle,
  DpToggleForm,
  DpTooltipIcon,
  DpTransitionExpand,
  DpTreeList,
  DpUploadFiles,
  DpVideoPlayer,
  getFileIdsByHash,
  MultistepNav
} = await import('./components/')

let {
  CleanHtml,
  Tooltip,
  VPopover
} = await import('./directives')

let {
  attributes,
  length
} = await import('./shared')

let {
  exactlengthHint,
  maxlengthHint,
  minlengthHint
} = await import('./utils')

let { prefixClass } = await import('./lib/')

let { prefixClassMixin } = await import('./mixins/')

export default {
  attributes,
  length,
  DpButton,
  DpDetails,
  DpIcon,
  DpInput,
  DpLabel,
  DpLoading,
  dataTableSearch,
  DpAccordion,
  DpAnonymizeText,
  DpAutocomplete,
  DpBulkEditHeader,
  DpButtonIcon,
  DpButtonRow,
  DpCard,
  DpChangeStateAtDate,
  DpCheckbox,
  DpCheckboxGroup,
  DpColumnSelector,
  DpContextualHelp,
  DpCopyPasteButton,
  DpDashboardTaskCard,
  DpDataTable,
  DpDataTableExtended,
  DpDatepicker,
  DpDateRangePicker,
  DpDatetimePicker,
  DpEditableList,
  DpEditor,
  DpFlyout,
  DpFormRow,
  DpHeightLimit,
  DpInlineNotification,
  DpModal,
  DpMultiselect,
  DpNotifyContainer,
  DpObscure,
  DpPager,
  DpProgressBar,
  DpRadio,
  DpRegisterFlyout,
  DpResettableInput,
  DpSearchField,
  DpSelect,
  DpSelectPageItemCount,
  DpSkeletonBox,
  DpSlidebar,
  DpSlidingPagination,
  DpSplitButton,
  DpStickyElement,
  DpSwitcher,
  DpTab,
  DpTableCard,
  DpTableCardListHeader,
  DpTabs,
  DpTextArea,
  DpTextWrapper,
  DpTimePicker,
  DpToggle,
  DpToggleForm,
  DpTooltipIcon,
  DpTransitionExpand,
  DpTreeList,
  DpUploadFiles,
  DpVideoPlayer,
  getFileIdsByHash,
  MultistepNav,
  CleanHtml,
  prefixClass,
  prefixClassMixin,
  Tooltip,
  VPopover,
  exactlengthHint,
  maxlengthHint,
  minlengthHint
}
